# Generated by Django 2.2.15 on 2020-11-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services1', '0006_auto_20201107_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('street_address1', models.CharField(max_length=100)),
                ('street_address2', models.CharField(max_length=100)),
                ('town_or_city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services1.Package')),
            ],
        ),
    ]
