# Generated by Django 2.2.15 on 2020-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
