# Generated by Django 2.2.15 on 2020-10-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services1', '0003_auto_20201006_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yearly',
            new_name='Packages',
        ),
        migrations.DeleteModel(
            name='Monthly',
        ),
        migrations.DeleteModel(
            name='One',
        ),
        migrations.AlterModelOptions(
            name='packages',
            options={'verbose_name_plural': 'Package'},
        ),
    ]
