# Generated by Django 2.2.15 on 2020-11-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services1', '0005_auto_20201010_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Package'},
        ),
    ]
